/**
 * This is automatically generated by sprout plug-in.
 */
package nexcore.sprout.showcase.mvc.interceptors;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * 
 * @since 	
 * @author Administrator
 */
@Controller
@RequestMapping("/interceptors")
public class InterceptorsController {
	
	@RequestMapping(value="checkinterceptor", method=RequestMethod.GET)
	public @ResponseBody String checkInterceptor() {
		return "office check ";
	}

	@RequestMapping(value="officeopen", method=RequestMethod.GET)
	public @ResponseBody String officeOpen() {
		return "interceptor : office open ";
	}
	
	@RequestMapping(value="officenotopen", method=RequestMethod.GET)
	public @ResponseBody String notOpen() {
		return "interceptor : office not open ";
	}
}