-- 파일 업로드 테이블
CREATE TABLE AMS_UPLOAD_FILE (
    PROGRAM_ID      VARCHAR(255) NOT NULL,
    DOC_ID          VARCHAR(50) NOT NULL,
    TYPE_ID         VARCHAR(10),
    FILE_ID         VARCHAR(50) NOT NULL,
    FILE_NAME       VARCHAR(100),
    FILE_PATH       VARCHAR(255),    
    FILE_SIZE       DECIMAL(15, 5),
    CREATE_USER     VARCHAR(50),
    CREATE_TIME     VARCHAR(14),
    CONSTRAINT PK_AMS_UPLOAD_FILE PRIMARY KEY (PROGRAM_ID, DOC_ID, FILE_ID)
);